# Generated by Django 4.0.7 on 2024-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating_sum',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
